# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Adel Lahlou
tagline:          "Site about a developer, growing data scientist, and occasionally food."
description:      "Site about a developer, growing data scientist, and occasionally food."
url:              http://adellahlou.com
baseurl:          /

author:
  name:           'Adel Lahlou'
  url:            https://github.com/adellahlou

paginate:         5

# Custom vars
version:          0.1.0

github:
  repo:           https://github.com/adellahlou


# Collections
collections:
  projects:
